apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:41:04Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1636"
  uid: 24c3ca8f-a083-4b68-9c6c-082aaabf152a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.64.50
  clusterIPs:
  - 10.102.64.50
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31537
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
